[theme]
base = "dark"
primaryColor = "#ED6941"
backgroundColor = "#141414"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#E7E7E8"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = false
